# Generated by Django 4.1.5 on 2024-08-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_first_name_alter_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='=$5p8n@77mg(&^r7a99', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='=$5p8n@77mg(&^r7a99', max_length=1000),
        ),
    ]
