# Generated by Django 4.2.4 on 2024-02-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_time', models.CharField(max_length=200)),
                ('transaction_reference', models.CharField(max_length=400)),
                ('transaction_description', models.CharField(max_length=100)),
                ('linking_reference', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('card_country', models.CharField(max_length=200)),
                ('is_Nigerian_Card', models.CharField(max_length=200)),
                ('prev_Linking_Reference', models.CharField(max_length=200)),
                ('transfer_amount', models.CharField(max_length=400)),
                ('transaction_Fee', models.CharField(max_length=400)),
                ('fee', models.CharField(max_length=400)),
                ('status', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=500)),
                ('account_No', models.CharField(max_length=100)),
                ('channel', models.CharField(max_length=100)),
                ('channel_Type', models.CharField(max_length=100)),
                ('is_International', models.CharField(max_length=100)),
                ('mode', models.CharField(max_length=100)),
                ('transType', models.CharField(max_length=100)),
                ('settlement_Amount', models.CharField(max_length=100)),
                ('refund_Amount', models.CharField(max_length=100)),
                ('gateway_Response_Code', models.CharField(max_length=200)),
                ('gateway_response_Message', models.CharField(max_length=100)),
            ],
        ),
    ]
