# Generated by Django 4.2.4 on 2024-02-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazox', '0002_transactions_event_transactions_has_dispute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='event',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='gateway_response_Message',
            field=models.CharField(default=' ', max_length=400),
        ),
    ]
