# Generated by Django 4.1.5 on 2024-09-02 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nazox', '0003_alter_transactions_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logString', models.CharField(default='No activity', max_length=1000)),
                ('userID', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=250)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
